// <auto-generated />
using Knowlead.Common;
using Knowlead.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Knowlead.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20170713180328_IsEmailSentNotifications")]
    partial class IsEmailSentNotifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26286")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knowlead.DomainModel.BlobModels._Blob", b =>
                {
                    b.Property<Guid>("BlobId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlobType")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Extension");

                    b.Property<string>("Filename");

                    b.Property<long>("Filesize");

                    b.Property<Guid>("UploadedById");

                    b.HasKey("BlobId");

                    b.ToTable("Blobs");

                    b.HasDiscriminator<string>("BlobType").HasValue("_Blob");
                });

            modelBuilder.Entity("Knowlead.DomainModel.CallModels._Call", b =>
                {
                    b.Property<Guid>("CallId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CallType")
                        .IsRequired();

                    b.Property<Guid>("CallerId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<double>("Duration");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("FailReason");

                    b.Property<bool>("Failed");

                    b.HasKey("CallId");

                    b.HasIndex("CallerId");

                    b.ToTable("Calls");

                    b.HasDiscriminator<string>("CallType").HasValue("_Call");
                });

            modelBuilder.Entity("Knowlead.DomainModel.ChatModels.Friendship", b =>
                {
                    b.Property<Guid>("ApplicationUserSmallerId");

                    b.Property<Guid>("ApplicationUserBiggerId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("LastActionById");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("ApplicationUserSmallerId", "ApplicationUserBiggerId");

                    b.HasIndex("ApplicationUserBiggerId");

                    b.HasIndex("LastActionById");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Knowlead.DomainModel.FeedbackModels._Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FeedbackText")
                        .IsRequired();

                    b.Property<int>("FosId");

                    b.Property<float>("Rating");

                    b.Property<Guid>("StudentId");

                    b.Property<Guid>("TeacherId");

                    b.Property<string>("TeacherReply");

                    b.HasKey("FeedbackId");

                    b.HasIndex("FosId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Feedbacks");

                    b.HasDiscriminator<string>("Category").HasValue("_Feedback");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LibraryModels.Notebook", b =>
                {
                    b.Property<int>("NotebookId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedById");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Markdown");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PrimaryColor")
                        .IsRequired();

                    b.Property<string>("SecondaryColor")
                        .IsRequired();

                    b.HasKey("NotebookId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LibraryModels.StickyNote", b =>
                {
                    b.Property<int>("StickyNoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedById");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NoteText");

                    b.HasKey("StickyNoteId");

                    b.HasIndex("CreatedById");

                    b.ToTable("StickyNotes");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Core.Achievement", b =>
                {
                    b.Property<int>("CoreLookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Desc")
                        .IsRequired();

                    b.Property<Guid>("ImageBlobId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CoreLookupId");

                    b.HasIndex("ImageBlobId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Core.FOS", b =>
                {
                    b.Property<int>("CoreLookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("ParentFosId");

                    b.Property<bool>("Unlocked");

                    b.HasKey("CoreLookupId");

                    b.HasIndex("ParentFosId");

                    b.ToTable("FOS");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Core.Language", b =>
                {
                    b.Property<int>("CoreLookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CoreLookupId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Core.Reward", b =>
                {
                    b.Property<int>("CoreLookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<int>("MinutesReward");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PointsReward");

                    b.HasKey("CoreLookupId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Geo.Country", b =>
                {
                    b.Property<int>("GeoLookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("GeoLookupId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Geo.State", b =>
                {
                    b.Property<int>("GeoLookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StatesCountryId");

                    b.HasKey("GeoLookupId");

                    b.HasIndex("StatesCountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Knowlead.DomainModel.NotificationModels.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("ForApplicationUserId");

                    b.Property<Guid?>("FromApplicationUserId");

                    b.Property<bool>("IsEmailSent");

                    b.Property<string>("NotificationType")
                        .IsRequired();

                    b.Property<int?>("P2pId");

                    b.Property<int?>("P2pMessageId");

                    b.Property<DateTime>("ScheduledAt");

                    b.Property<DateTime?>("SeenAt");

                    b.HasKey("NotificationId");

                    b.HasIndex("ForApplicationUserId");

                    b.HasIndex("FromApplicationUserId");

                    b.HasIndex("P2pId");

                    b.HasIndex("P2pMessageId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2P", b =>
                {
                    b.Property<int>("P2pId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BookmarkCount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedById");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateTimeAgreed");

                    b.Property<DateTime?>("Deadline");

                    b.Property<int>("DifficultyLevel");

                    b.Property<int>("FosId");

                    b.Property<int>("InitialPrice");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OfferCount");

                    b.Property<int?>("PriceAgreed");

                    b.Property<Guid?>("ScheduledWithId");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("TeacherReady");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("P2pId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FosId");

                    b.HasIndex("ScheduledWithId");

                    b.ToTable("P2Ps");
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PBookmark", b =>
                {
                    b.Property<int>("P2pId");

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("P2pId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("P2PBookmarks");
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PFile", b =>
                {
                    b.Property<int>("P2pId");

                    b.Property<Guid>("FileBlobId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("P2pId", "FileBlobId");

                    b.HasIndex("FileBlobId");

                    b.ToTable("P2PFiles");
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PImage", b =>
                {
                    b.Property<int>("P2pId");

                    b.Property<Guid>("ImageBlobId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("P2pId", "ImageBlobId");

                    b.HasIndex("ImageBlobId");

                    b.ToTable("P2PImages");
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PLanguage", b =>
                {
                    b.Property<int>("P2pId");

                    b.Property<int>("LanguageId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("P2pId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("P2PLanguages");
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PMessage", b =>
                {
                    b.Property<int>("P2pMessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DateTimeOffer");

                    b.Property<Guid>("MessageFromId");

                    b.Property<Guid>("MessageToId");

                    b.Property<int?>("OfferAcceptedId");

                    b.Property<int>("P2pId");

                    b.Property<int>("PriceOffer");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("P2pMessageId");

                    b.HasIndex("MessageFromId");

                    b.HasIndex("MessageToId");

                    b.HasIndex("OfferAcceptedId");

                    b.HasIndex("P2pId");

                    b.ToTable("P2PMessages");
                });

            modelBuilder.Entity("Knowlead.DomainModel.StatisticsModels.PlatformFeedback", b =>
                {
                    b.Property<Guid>("PlatformFeedbackId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Feedback");

                    b.Property<Guid>("SubmittedById");

                    b.HasKey("PlatformFeedbackId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("PlatformFeedbacks");
                });

            modelBuilder.Entity("Knowlead.DomainModel.TransactionModels.AccountTransaction", b =>
                {
                    b.Property<Guid>("AccountTransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("FinalMinutesBalance");

                    b.Property<int>("FinalPointsBalance");

                    b.Property<int>("MinutesChangeAmount");

                    b.Property<int>("PointsChangeAmount");

                    b.Property<string>("Reason")
                        .IsRequired();

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("AccountTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutMe");

                    b.Property<int>("AccessFailedCount");

                    b.Property<float>("AverageRating");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int?>("CountryId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool?>("IsMale");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<int?>("MotherTongueId");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<Guid?>("ProfilePictureId");

                    b.Property<string>("SecurityStamp");

                    b.Property<int?>("StateId");

                    b.Property<int>("Status");

                    b.Property<string>("Surname");

                    b.Property<string>("Timezone");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("MotherTongueId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProfilePictureId");

                    b.HasIndex("StateId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserInterest", b =>
                {
                    b.Property<Guid>("ApplicationUserId");

                    b.Property<int>("FosId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Stars");

                    b.HasKey("ApplicationUserId", "FosId");

                    b.HasIndex("FosId");

                    b.ToTable("ApplicationUserInterests");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserLanguage", b =>
                {
                    b.Property<Guid>("ApplicationUserId");

                    b.Property<int>("LanguageId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("ApplicationUserId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("ApplicationUserLanguages");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserReferral", b =>
                {
                    b.Property<Guid>("NewRegistredUserId");

                    b.Property<Guid>("ReferralUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("UserRegistred");

                    b.HasKey("NewRegistredUserId", "ReferralUserId");

                    b.HasIndex("ReferralUserId");

                    b.ToTable("ApplicationUserReferrals");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserReward", b =>
                {
                    b.Property<Guid>("ApplicationUserId");

                    b.Property<int>("RewardId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("ApplicationUserId", "RewardId");

                    b.HasIndex("RewardId");

                    b.ToTable("ApplicationUserRewards");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.UserAchievement", b =>
                {
                    b.Property<int>("UserAchievementId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AchievementId");

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.UserCertificate", b =>
                {
                    b.Property<int>("UserCertificateId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Desc");

                    b.Property<Guid?>("ImageBlobBlobId");

                    b.Property<int>("ImageBlobId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("UserCertificateId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ImageBlobBlobId");

                    b.ToTable("UserCertificates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Knowlead.DomainModel.BlobModels.FileBlob", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.BlobModels._Blob");


                    b.HasIndex("UploadedById");

                    b.ToTable("FileBlob");

                    b.HasDiscriminator().HasValue("File");
                });

            modelBuilder.Entity("Knowlead.DomainModel.BlobModels.ImageBlob", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.BlobModels._Blob");

                    b.Property<int>("Height");

                    b.Property<int>("Width");

                    b.HasIndex("UploadedById");

                    b.ToTable("ImageBlob");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("Knowlead.DomainModel.CallModels.FriendCall", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.CallModels._Call");

                    b.Property<Guid>("CallReceiverId");

                    b.HasIndex("CallReceiverId");

                    b.ToTable("FriendCall");

                    b.HasDiscriminator().HasValue("FriendCall");
                });

            modelBuilder.Entity("Knowlead.DomainModel.CallModels.P2PCall", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.CallModels._Call");

                    b.Property<Guid>("CallReceiverId")
                        .HasColumnName("P2PCall_CallReceiverId");

                    b.Property<int>("P2PId");

                    b.HasIndex("CallReceiverId");

                    b.HasIndex("P2PId");

                    b.ToTable("P2PCall");

                    b.HasDiscriminator().HasValue("P2PCall");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.FeedbackModels.ClassFeedback", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.FeedbackModels._Feedback");


                    b.ToTable("Feedbacks");

                    b.HasDiscriminator().HasValue("Class");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.FeedbackModels.CourseFeedback", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.FeedbackModels._Feedback");


                    b.ToTable("Feedbacks");

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.FeedbackModels.P2PFeedback", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.FeedbackModels._Feedback");

                    b.Property<int>("Expertise");

                    b.Property<int>("Helpful");

                    b.Property<int>("P2pId");

                    b.HasIndex("P2pId");

                    b.ToTable("Feedbacks");

                    b.HasDiscriminator().HasValue("P2P");
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.FeedbackModels.QuestionFeedback", b =>
                {
                    b.HasBaseType("Knowlead.DomainModel.FeedbackModels._Feedback");


                    b.ToTable("Feedbacks");

                    b.HasDiscriminator().HasValue("Question");
                });

            modelBuilder.Entity("Knowlead.DomainModel.CallModels._Call", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "Caller")
                        .WithMany()
                        .HasForeignKey("CallerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.ChatModels.Friendship", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUserBigger")
                        .WithMany()
                        .HasForeignKey("ApplicationUserBiggerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUserSmaller")
                        .WithMany()
                        .HasForeignKey("ApplicationUserSmallerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "LastActionBy")
                        .WithMany()
                        .HasForeignKey("LastActionById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.FeedbackModels._Feedback", b =>
                {
                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.FOS", "Fos")
                        .WithMany()
                        .HasForeignKey("FosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.LibraryModels.Notebook", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.LibraryModels.StickyNote", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Core.Achievement", b =>
                {
                    b.HasOne("Knowlead.DomainModel.BlobModels.ImageBlob", "ImageBlob")
                        .WithMany()
                        .HasForeignKey("ImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Core.FOS", b =>
                {
                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.FOS", "ParentFos")
                        .WithMany()
                        .HasForeignKey("ParentFosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.Geo.State", b =>
                {
                    b.HasOne("Knowlead.DomainModel.LookupModels.Geo.Country", "StatesCountry")
                        .WithMany()
                        .HasForeignKey("StatesCountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.NotificationModels.Notification", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ForApplicationUser")
                        .WithMany()
                        .HasForeignKey("ForApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "FromApplicationUser")
                        .WithMany()
                        .HasForeignKey("FromApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany()
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2PMessage", "P2pMessage")
                        .WithMany()
                        .HasForeignKey("P2pMessageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2P", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.FOS", "Fos")
                        .WithMany()
                        .HasForeignKey("FosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ScheduledWith")
                        .WithMany()
                        .HasForeignKey("ScheduledWithId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PBookmark", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany()
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PFile", b =>
                {
                    b.HasOne("Knowlead.DomainModel.BlobModels.FileBlob", "FileBlob")
                        .WithMany()
                        .HasForeignKey("FileBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany("P2PFiles")
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PImage", b =>
                {
                    b.HasOne("Knowlead.DomainModel.BlobModels.ImageBlob", "ImageBlob")
                        .WithMany()
                        .HasForeignKey("ImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany("P2PImages")
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PLanguage", b =>
                {
                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany("P2PLanguages")
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.P2PModels.P2PMessage", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "MessageFrom")
                        .WithMany()
                        .HasForeignKey("MessageFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "MessageTo")
                        .WithMany()
                        .HasForeignKey("MessageToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2PMessage", "OfferAccepted")
                        .WithMany()
                        .HasForeignKey("OfferAcceptedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany()
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.StatisticsModels.PlatformFeedback", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.TransactionModels.AccountTransaction", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUser", b =>
                {
                    b.HasOne("Knowlead.DomainModel.LookupModels.Geo.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.Language", "MotherTongue")
                        .WithMany()
                        .HasForeignKey("MotherTongueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.BlobModels.ImageBlob", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.LookupModels.Geo.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserInterest", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserInterests")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.FOS", "Fos")
                        .WithMany()
                        .HasForeignKey("FosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserLanguage", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserLanguages")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserReferral", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "NewRegistredUser")
                        .WithMany()
                        .HasForeignKey("NewRegistredUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ReferralUser")
                        .WithMany()
                        .HasForeignKey("ReferralUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.ApplicationUserReward", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.UserAchievement", b =>
                {
                    b.HasOne("Knowlead.DomainModel.LookupModels.Core.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.UserModels.UserCertificate", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.BlobModels.ImageBlob", "ImageBlob")
                        .WithMany()
                        .HasForeignKey("ImageBlobBlobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.BlobModels.FileBlob", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.BlobModels.ImageBlob", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.CallModels.FriendCall", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "CallReceiver")
                        .WithMany()
                        .HasForeignKey("CallReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.CallModels.P2PCall", b =>
                {
                    b.HasOne("Knowlead.DomainModel.UserModels.ApplicationUser", "CallReceiver")
                        .WithMany()
                        .HasForeignKey("CallReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2P")
                        .WithMany()
                        .HasForeignKey("P2PId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowlead.DomainModel.LookupModels.FeedbackModels.P2PFeedback", b =>
                {
                    b.HasOne("Knowlead.DomainModel.P2PModels.P2P", "P2p")
                        .WithMany()
                        .HasForeignKey("P2pId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
